apiVersion: apps/v1
kind: Deployment
metadata:
  name: todobackend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todobackend
  template:
    metadata:
      name: todobackend
      labels:
        app: todobackend
        tier: backend
    spec:
      containers:
      - name: todobackend
        readinessProbe:
          httpGet:
            path: /hello
            port: 8080
          initialDelaySeconds: 1
          timeoutSeconds: 1
          periodSeconds: 1
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /todos/
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: POSTGRES_HOST
          value: postgresdb
        - name: INSPECTIT_METRICS_JMX_ENABLED
          value: 'true'
        - name: INSPECTIT_EXPORTERS_TRACING_JAEGER_URL
          value: 'http://jaeger.monitoring:14268/api/traces'
        - name: INSPECTIT_SERVICE_NAME
          value: 'todobackend'
        image: novatec/technologyconsulting-containerexerciseapp-todobackend:v0.2-ocelot
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: todobackend
  name: todobackend
spec:
  type: ClusterIP
  ports:
  - name: http-todobackend
    port: 8080
  - name: http-metrics
    port: 8888
  selector:
    app: todobackend
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: todobackend
spec:
  endpoints:
  - interval: 15s
    port: http-metrics
  selector:
    matchLabels:
      app: todobackend
